### ISSUE TITLE
Is master broken?

### ISSUE THREAD

**Issue by tuchk4** [thtliife/create-react-app-storybook-scripts-fork#1]
Is it broken right now?
I don't see (in current master) any scripts and templates that relates to storybook

**Comment by thtliife** [comment]
I have left master alone, and done all work in the storybook branch....
This way it is much easier to merge in changes from the original create-react-app...

**Comment by thtliife** [comment]
@tuchk4 something seems to have gone horribly wrong with this repo....
I have created a new fork now, with a working branch for storybook scripts...

It lives [here](https://github.com/thtliife/create-react-app/tree/storybook-scripts)

Note that the react-scripts folder is the react-storybook-scripts folder in real life, I have left the name the same once again to facilitate proper upstream merges of changes...
